language: php

php:
    - 7.0
    - 7.1

sudo: false

before_install:
  - composer self-update

install:
  - composer update --prefer-source $COMPOSER_FLAGS

script: phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover